### ISSUE TITLE
Dynamic variable offer

### ISSUE THREAD

**Issue by sondotpin** [casey/runestone#105]
### Current situation
SELLER just can place a fixed amount of Rune to sell, this is look like we wrapped a amount Fungible token in an Non-Fungible token. and the trade look like an Non-Fungible token trading
### Idea

SELLER place OFFER_UTXO contain these information

```OFFER_UTXO  = TERM_TAG AMOUNT_RUNE AMOUNT_SATS MINIMUM_SATS_RECEIVED ```

psbt of seller look like:

```
OFFER_UTXO           | BTC_RETURN_TO_BUYER (=BTC_IN_OFFER_UTXO + MINIMUM_SATS_RECEIVED)
                      | OP_RETURN
```
psbt of buyer look like:

```
OFFER_UTXO          | BTC_RETURN_TO_SELLER (=BTC_IN_OFFER_UTXO + MINIMUM_SATS_RECEIVED)
BTC_OF_BUYER      | OP_RETURN [id, 0, 2]
                      | RUNE_OUTPUT
                      | ADDITIONAL_BTC_TO_SELLER
```
depends on sats that buyers set to ADDITIONAL_BTC_TO_SELLER, amount of rune send to buyer will be calculated

@casey

**Comment by casey** [comment]
This looks the same as #58. Can you explain the difference?

**Comment by sondotpin** [comment]
In #58 amount of Rune sell & amount of Sats want to receive is fixed. I want to design a scenario that example:

`Seller want to sell 1000Rune to get 1000 sats`

then

`buyer deposit 100 sats and get 100Rune`

**Comment by casey** [comment]
Actually, that's how the current design works. See this comment for the steps: https://github.com/casey/runestone/issues/58#issuecomment-1767777904

In essence, the seller specifies an exchange rate in sats/rune, and the buyer receives sats according to that exchange rate and how many sats he allocates to the seller.
