### ISSUE TITLE
Protection from front-running via commit/reveal

### ISSUE THREAD

**Issue by casey** [casey/runestone#120]
We need a commit/reveal scheme where the commitment and the reveal happen in separate transactions. This is necessary because whatever we do in a single transaction can be copied.

Properties we want:
1. Rune cannot be determined from commitment
2. Commitment cannot be copied by a third party
3. One reveal is visible, can't commit and reveal before the reveal is mined

So, with the following in mind, an etching is valid if:
- An input witness contains a data push of the rune name
- The transaction that created that input was mined at least 144 blocks ago

1. Since the witness is a script, the committer can include a blinding factor in the script
2. The commitment script can include an OP_CHECKSIG with the committers public key. The commitment can be copied by a third party creating an output with the same address, but they cannot reveal from it because they do not know the private key
3. Once the reveal transaction is published, as long as it is mined within 144 blocks, it cannot be front-run, because a different commit for the same rune cannot be revealed before the reveal is mined

144 blocks is chosen because the primary reason a reveal wouldn't be mined is fee uncertainty, and 144 blocks both lets the etcher catch a 24 hour dip in the fees, and plenty of time to fee-bump the transaction.

This prevents front-running, but not collisions. A commitment should not be required for automatically allocated runes.

**Comment by cliobitcoinbank** [comment]
This is a great idea, please try to implement for day 1 so the wallfacers can all mint on day 1 sophon free.

**Comment by casey** [comment]
> This is a great idea, please try to implement for day 1

I'm definitely going to try, although this has implications for UX, namely that deploys would take 6+ blocks to activate.

> wallfacers

😂

**Comment by satsondefi** [comment]
144 blocks, 1 + 4 + 4 equals 9, 

Block 84.000 8 + 4 equals =12, 1+ 2= 3.  

3, 6 and 9. Putting Nikola's theory  in Runestone dna @casey

**Comment by satsondefi** [comment]
144 blocks will let the etcher have 24 hours. 

2 + 4 = 6.

Irs written kek.

**Comment by casey** [comment]
It is done!
