### ISSUE TITLE
Should iniital etching be able to allocate more than limit?

### ISSUE THREAD

**Issue by casey** [casey/runestone#124]
I'm leaning towards no. Either way, make sure there's a test.

**Comment by sondotpin** [comment]
I think it can. because otherwise, init with limit is almost meaningless to the creator. Creators want init etching to create a tokenomics according to their own ideas

**Comment by casey** [comment]
We decided to allow the initial etching transaction to allocate any amount of the supply. We're making this transparent on the `/rune` page, so that every rune shows the premine amount, which is the amount allocated by the initial transaction.
