### ISSUE TITLE
TODO: Draft Technical Documentation

### ISSUE THREAD

**Issue by Psifour** [casey/runestone#13]
"Write a plain-english specification."

**Comment by Psifour** [comment]
The technical specification is probably the single most important aspect and I look forward to following it closely.

For non-technical readers, is it reasonable to assume that there is a desire to create an additional **simpler** form of the documentation that is designed upfront for easy localization and consumption by users (as opposed to developers)?

**Comment by casey** [comment]
Yah, I think so. There should be a technical spec, as well as a high level description. As always though, there's a certain tension between the technical spec and the reference implementation, and when they disagree, one or the other might be amended.

**Comment by Psifour** [comment]
> Yah, I think so. There should be a technical spec, as well as a high level description. As always though, there's a certain tension between the technical spec and the reference implementation, and when they disagree, one or the other might be amended.

If I may suggest it, it should be defined which is the source of truth for this implementation. I personally lean towards making the written technical specification is authoritative as this means that there is room for solving bugs and design defects (hopefully not needed) in the reference implementation.

**Comment by casey** [comment]
I don't actually know if this is possible or desirable. If there's a bug in the implementation, it may very well wind up that fixing the implementation to match the spec is disruptive, so the spec must be amended to match the implementation. Also, specs are often underspecified, whereas implementations are not. An implementation might not have the desired behavior in all cases, but it will have *some* behavior.

**Comment by casey** [comment]
Closing in favor of #57, which covers both high-level and low-level documentation.
