### ISSUE TITLE
Display pre-mine percentage on /rune page

### ISSUE THREAD

**Issue by casey** [casey/runestone#134]
Perhaps we should also delineate between runes that have a long open etching vs a short open etching. Perhaps with etchings which were open for less than one difficulty adjustment getting a short open etching warning or badge.

**Comment by lifofifoX** [comment]
I hope you give it a serious thought to have block height activation for features that allows pre-mining and small window/limited supply open etchings.

Would hate to see a tiny group pre-mine the full supplies for first the few tokens and later attempt to sell those for millions of dollars. It'd completely go against the ethos of _"for degens"_. Absent an enforcement at the protocol level, it'll most certainly happen. An equivalent of this would be a single entity owning the first 100k inscriptions.

Sorry for being a broken record!

**Comment by lyndoco** [comment]
@devords if you reference BRC-20, it's really only the *first* instance of a token ($ORDI) that inherited a disproportional sum of the *early inscribooor* value bargain discount.

With bitcoin we were fortunate to have Satoshi's coins get effectively vaulted - with inscriptions, we were also fortune enough to have Casey inscribe and protek #0. I agree with the idea of symbolically etching the first rune and suffocating its secondary value... but I don't know if that materially does anything to advance the protocol, or make it more "fair". 

Could be wrong. Just don't see the theoretical benefits outweighing the added complexity & unanticipated externalities.

**Comment by lifofifoX** [comment]
@lyndoco BRC20 isn't necessarily a fair comparison. When it launched, Ordinals were dead. It didn't garner the attention of the entire space and outsiders, until months later. It's fair to recognize that Runes are a _different_ ball game and the launch will be one of the most highly anticipated launches in Bitcoin's entire history.

My original proposal was essentially similar to block height activation for ticker length, but extending it to certain other features offered by the protocol.

End of the day, I'd like Casey to consider all the possible outcomes (esp. the one where a small number of people would pre-mine entire supplies of first 5-10 tokes and attempting to sell for ridiculous prices) and do what's best for the long term health of the ecosystem. % of of people opposing fair open mints for first couple of runes tokens would be extremely small. But perhaps, there are other alternatives that offer a better balance re: protocol complexity and ensuring the fairest possible launch.

**Comment by casey** [comment]
The idea of pre-reserving just the first rune, and making it a fair mint with a long mint period, is actually an interesting idea. I don't think it's too complicated, it would make sure that rune 0 is fair mint, which will be the most memed and hyped rune, and reduce the incentive to spam the chain with massive fee transactions to try to get rune 0.

The main issue I see, aside from technical complexity, which isn't too bad, is that I would have to pick the name, currency symbol, divisibility, etching limit, and etching period. Aside from etching period, these are semi-arbitrary, mostly aesthetic choices, so it might be contentious.

**Comment by lifofifoX** [comment]
There are some cool looking unicode symbols resembling "R": ℜ Ꝛ Ꮢ Ɍ ɍ and more.

Maybe signet testing participants could vote on some choices!

**Comment by cliobitcoinbank** [comment]
The "fairness" of open mints is largely overblown, unless I were to monitor the mempool or the new runes page meticulously there will be an opportunity for someone to attempt to conceal that the open mint is occurring for a part of the open mint period.  Saotoshi seemed to understand that being so so early is effectively an unfair premine whether the process was technically available to everyone or not.  Technically fair is not fair, all the founders premined, it's fine as long as the total supply is fairly large.

**Comment by casey** [comment]
> The "fairness" of open mints is largely overblown, unless I were to monitor the mempool or the new runes page meticulously there will be an opportunity for someone to attempt to conceal that the open mint is occurring for a part of the open mint period.

I thought this myself, and agree that they can be gamed. However, in practice, they are dramatically fairer than other options.

**Comment by Rock-520** [comment]
I would like to ask if the cook token released by the chef team will serve as the first token on the rune main network, or will a new coin be cast? @casey

**Comment by cliobitcoinbank** [comment]
> I would like to ask if the cook token released by the chef team will serve as the first token on the rune main network, or will a new coin be cast? @casey

Chef team (runealpha.xyz) is on some other runes protocol having nothing to do with Ordinal's coming implementation of Runes.

**Comment by Rock-520** [comment]
> > I would like to ask if the cook token released by the chef team will serve as the first token on the rune main network, or will a new coin be cast? @casey
> 
> Chef team (runealpha.xyz) is on some other runes protocol having nothing to do with Ordinal's coming implementation of Runes.

Chef team (runealpha.xyz)  say on Twitter that they have no forked runes and only one rune 
https://twitter.com/runealpha_btc/status/1742599823075967018

**Comment by lifofifoX** [comment]
@Rock-Lee-520 Official runes protocol will be activated at next halving, block height 840,000. Ordinals.com will not index anything created prior to that block. Anyone is free to take ord source code and build their own indexes prior to that block height. However, those will not be indexed by Runes source code available on ordinals/ord.

**Comment by owenstrevor** [comment]
> The idea of pre-reserving just the first rune, and making it a fair mint with a long mint period, is actually an interesting idea. I don't think it's too complicated, it would make sure that rune 0 is fair mint, which will be the most memed and hyped rune, and reduce the incentive to spam the chain with massive fee transactions to try to get rune 0.
> 
> The main issue I see, aside from technical complexity, which isn't too bad, is that I would have to pick the name, currency symbol, divisibility, etching limit, and etching period. Aside from etching period, these are semi-arbitrary, mostly aesthetic choices, so it might be contentious.

Can keep it simple
Name: FirstRuneToken
Symbol: Rune
Divisibility: 8 digits (Same as BTC)
Supply: 21M (Same as BTC)
Etching Limit: 3.25 (Same as BTC post-halving)
Etching Period: This can't be open-ended?

**Comment by k2riddim** [comment]
Name: RuneZero
Symbol: Zero

**Comment by casey** [comment]
We could also hard-code a few of the first runes, someone suggested going all runes with 1-digit rune numbers, i.e, 0-9, with different parameters, like rune, symbol, limit, and deadline.

**Comment by runesenjoyer** [comment]
> The idea of pre-reserving just the first rune, and making it a fair mint with a long mint period, is actually an interesting idea. I don't think it's too complicated, it would make sure that rune 0 is fair mint, which will be the most memed and hyped rune, and reduce the incentive to spam the chain with massive fee transactions to try to get rune 0.
> 
> The main issue I see, aside from technical complexity, which isn't too bad, is that I would have to pick the name, currency symbol, divisibility, etching limit, and etching period. Aside from etching period, these are semi-arbitrary, mostly aesthetic choices, so it might be contentious.

If Rune "0" was deployed by you (you are the creator of the protocol after all), the success of Runes would increase tremendously. The entire space is worried that some VC backed team will somehow get the first Runes etching in a gas war, which they will then use to dump on the public. I truly think, a free & fair mint launched by yourself would get the protocol off to a great start, and would be a strong deterrent to the sharks currently running "I owe you's" on text inscriptions, which are meant to represent future Runes tokens. If the market knew you were launching the first token, these wealth extraction events on ordinals revolving around Runes would come to a halt.

Satoshi mined the first block, Domo deployed $ordi, and think you need to be the one to deploy the first Rune. 

As far as the fair & open mint, I'm not opposed to a model where you mint as many of the first token until a certain block ends the mint. Given the hype, that might end up being a hell of a payday for the miners.

I think the preferred method to fair mint is modeling the $Sats BRC-20 supply/mints per txn. That took months to mint out without causing relative disruption to the mempool.

**Comment by Rock-520** [comment]
I'm not opposed to the ordinals team to issue the first token, but I hope the team can consider the following issues

1. The chef team chose fair mint, and the runecoin team chose air-drop, which one can better reflect fair

2. BRC 20 first token $ ORDI The biggest problem is that few people are making ecology around it. As the first token, he needs to lead the development of the whole ecology, such as ERC 20 ETH

3. In fact, the chef team and the runecoin team have promoted the development and publicity of Rune protocol. For the ecological team that helps Rune protocol develop, it should be an alliance, rather than a boycott.

We would prefer to see an ecological prosperity, rather than a single king

![image](https://github.com/casey/runestone/assets/35133768/7586c78c-5d27-46c9-b09a-571a5f7fc69c)

**Comment by HubertusVIE** [comment]
For Bitcredit Protocol we need a properly working token to handle a serious digital asset which cannot be bitcoin. Currently we are using BRC20, but are considering an upgrade, either to Runes or Taproot Assets.  
What we need:
Best, the total supply can be controlled by a governance decision and the original deployer would determine minting and allocation. A possibility for the deployer to transfer the minting right in case governance changes.
This also means no front-running mempool chaos, which I understand comes with the "fair" mint used for non-useful meme tokens. (I am sure bitcoiners would not mind if there is less of that.)

**Comment by casey** [comment]
> the total supply can be controlled by a governance decision and the original deployer would determine minting and allocation

Governance is a very complicated topic, and there are no good implementations, as far as I'm aware. I think this is best handled outside of the runes protocol. On issuance, more than needed can be issued and held in a multisig, which can then bring supply online as needed.

> A possibility for the deployer to transfer the minting right in case governance changes.

When creating a rune, you can create an inscription at the same time. This inscription is only used for metadata, but there's no reason you couldn't give it special meaning. For example, you can have a protocol where minting rights are controlled by inscription X, and for a rune to be valid in that protocol, the parent inscription of that rune must be a child of inscription X. Thus, "minting rights" are controlled by inscription X, which can then be transferred according to the ordinals / inscription protocol.

**Comment by HubertusVIE** [comment]
1. Thanks and yes, governance is offline. 
2. More (treasury tokens): not a good solution for serious assets (non meme). We'd need governance to be able to control the mint, with no more tokens possible than decided at the time. Absolute limit would be good though. 
3. That "special meaning" would not be part of the standard runes protocol?

**Comment by casey** [comment]
> 3. That "special meaning" would not be part of the standard runes protocol?

That's correct, but it would be pretty easy to implement.

**Comment by HubertusVIE** [comment]
That would be great, if you want serious digital asset applications apart from memes, with their reputational issues.

**Comment by satsondefi** [comment]
> We could also hard-code a few of the first runes, someone suggested going all runes with 1-digit rune numbers, i.e, 0-9, with different parameters, like rune, symbol, limit, and deadline.

100% hard-code the first Rune Casey. People could use the statement of being the first 'actual' Rune when it can be indexed by Ordinals for malicious intent and scam a lot of people from their money by acting like they have somewhat of a utility. It will also cause confusion if people see that the first Rune etched actually would be RSIC, RuneX or RuneAlpha.

Imo Runes is going to be a protocol where the most fun stuff can be build on Bitcoin. Hope too see really fun communities building on it instead of these shitcoins projects that talk a big game by saying the have 'utility' lol.

**Comment by casey** [comment]
Moving to ord issue.
