### ISSUE TITLE
UTXO base disadvantages

### ISSUE THREAD

**Issue by sondotpin** [casey/runestone#135]
The advantages of UTXO-based systems in terms of security are indisputable; however, the consolidation of UTXOs results in excessively high gas fees. When degens, such as those involved with Fairmint they often incur significant gas fees. 

Do you have any idea of this problem @casey

**Comment by casey** [comment]
Being UTXO-based definitely has downsides. However, you can continuously consolidate, which shouldn't make fees too high. If you have a specific example of a transaction graph/usage pattern which pays high fees, that would be helpful, since it's hard to discuss in the abstract.

**Comment by sondotpin** [comment]
here @casey 
https://runealpha.xyz/txs/a49da6f65feb48ac84a0d9a0289ff0903cb9051c1cf3f472ce91b6f0cfdd1af5

**Comment by casey** [comment]
What would help would be knowing *why* that consolidation transaction was made. Why did the person making that consolidation transaction wind up with a bunch of separate inputs?

**Comment by sondotpin** [comment]
In Open etching man (currently Open etching is currently the most popular approach for launching runes)
1. user claim many times. Example 100 times
2. they want to transfer or trade all their Rune.

They need to consolidate at this case.

**Comment by casey** [comment]
True, but open etching is *supposed* to be expensive, otherwise the limit per claim is meaningless. So the additional cost of consolidating isn't an issue.
