### ISSUE TITLE
Gambling

### ISSUE THREAD

**Issue by casey** [casey/runestone#136]
We could allow users to wager runes at particular odds. This would be cool, however, since it would use the block hash as a source of randomness, it could be gamed by miners. A miner could acquire a substantial amount of runes, bet it at 2-1 odds, and only release a block if the bet paid off. If the amount of runes was substantial, this could dwarf the 50% of block rewards and fees that they would have to forgo.

**Comment by cliobitcoinbank** [comment]
Is there anything hard for miners to game like the hash they guess to mine a block or tie it to the total fees in the block or something?  Anything beyond their control that goes into a block?

**Comment by casey** [comment]
Miner's can't game the hash, the only way that they can game it is by not publishing blocks with hashes that cause them to lose their bet.

One possible solution to the MEV problem is allowing gambling, but not resolving the bet in the same block in which it is published. The bet would be resolved in the following block, forcing miners to mine two blocks in a row to game the bet.

**Comment by lopezi** [comment]
how could this possibly fit the dynamics of blockchain based parametric insurance?

**Comment by casey** [comment]
The creator of a rune would need to opt into this, so it isn't enabled for any rune that doesn't want it.

**Comment by casey** [comment]
Moving issues to ord.
