### ISSUE TITLE
Runestones may not create a rune with an open etching, and allocate it

### ISSUE THREAD

**Issue by casey** [casey/runestone#138]
This makes the implementation simpler, and means that either a rune is entirely allocated by premine, or by an open eching, no inbetween.

The implementation should check if i's an open etching, and if so, set the allocatable amount to 0.

**Comment by Rock-520** [comment]
I am in complete agreement.

**Comment by casey** [comment]
We decided to allow this. A rune may be etched with a premine, which is any allocation made in the etching transaction. Premines are displayed on the `/rune` page for transparency.
