### ISSUE TITLE
TODO: Payload Sentinel Value/Signature

### ISSUE THREAD

**Issue by Psifour** [casey/runestone#14]
"Finalize the payload signature. In order to discourage the proliferation of incompatible issuance transactions, this implementation uses a push of the bytes "RUNE_TEST" after an OP_RETURN to indicate a rune payload. This is intended to be temporary, and should be changed to a final."

**Comment by Psifour** [comment]
I am a firm proponent of "R" or "RUNE" Obviously wasting 3 bytes of our very limited space (of functional space) doesn't seem optimal.

**Comment by summraznboi** [comment]
As commented in the block activation height proposal, I think not committing to the final value until the protocol is ready will help reduce any speculation before launch.

**Comment by Psifour** [comment]
Fully agree

**Comment by casey** [comment]
Yah, agreed.

**Comment by casey** [comment]
Closing in favor of combined block height and payload signature issue #59.
