### ISSUE TITLE
Make claims more efficient

### ISSUE THREAD

**Issue by casey** [casey/runestone#141]
Claims ID are potentially large, since the 48th bit is set. Perhaps they could be made more efficient?

- Rename claims to `mints`
- Don't use a modified ID to encode a mint. Use a `mint` tag, which has a rune ID as a value. If that rune is mintable, add the maximum amount that can be minted to the available balances. Avoids needing an edict to claim at all. By default with no edicts, the maximum amount claimable will go to the first destination output.
- Don't allow more than one mint per transaction. The idea behind one mint per transaction is that they should be costly. Minting multiple runes per transaction bypasses this by amortizing the cost of one transaction among multiple mints.

**Comment by cliobitcoinbank** [comment]
It may be so illogical that someone would mint (etch?) less than the maximum amount of runes in each mint that it could be omitted and just assumed all claims are of the maximum size unless otherwise stated??

**Comment by casey** [comment]
The maximum amount of runes is 2**128, which is totally insane, like orders of magnitude more particles in the universe, so we wouldn't want to default to that, and defaulting to something else would be unexpected.

**Comment by cliobitcoinbank** [comment]
Sorry I'm botching the terminology here, "claims" of a rune already deployed "etched?" during the open mint period should default to the maximum size defined by the deploy/  It makes no sense for every claimant to have to specify the max amount onchain over and over in every claim the way brc20 does, the default "claim" should be the maximum size defined by the deployer, whatever you call the initial contract thing.  Sorry if claim instead refers to the ticker name, I am referring to the claims of tokens issued after the ticker is deployed.

**Comment by casey** [comment]
Gotcha, I see what you mean. That makes sense. We should make claiming 0 mean claiming the maximum amount allowable.
