### ISSUE TITLE
Release a library with runestone encoding and decoding

### ISSUE THREAD

**Issue by casey** [casey/runestone#142]

**Comment by sondotpin** [comment]
Can I write a js/ts version

**Comment by cliobitcoinbank** [comment]
does this exist for ordinals? i just saw the new decode feature in 0.14 and I'm trying to decode or parse ordinals from rawtxs but it would be nice to have something lighter than ord.

**Comment by sneurlax** [comment]
I can contribute to a Flutter/Dart package to this effect.

I see existing work in:
 - Old Rust code: https://github.com/casey/runestone/blob/352d8ae0654d7ad4699c9d934d24379c20c506a8/src/runestone.rs
 - Python: https://github.com/Anarkoic/runes
 - Typescript: https://github.com/luminexord/runes

**Comment by lugondev** [comment]
I have completed the full function decipher and encipher using typescript, I will open source it soon, and maybe there will be another version using golang.

**Comment by afeezaziz** [comment]
Was thinking with encoding/decoding, you can write client side validation and put the state in OP_RETURN @casey

**Comment by mcbagz** [comment]
Along these lines, has anyone considered making a plugin/extension? I have been tracking the testnet, and there is a flag on mempool.space for "RUNE_TEST" transactions, and it would be great to have a tool that can decipher the rest of the transaction details on the site.

**Comment by afeezaziz** [comment]
> sondotpin

you have an update on this?

**Comment by afeezaziz** [comment]
I want to volunteer to work on, using Python:

1. encode runes to OP_RETURN
2. decode runes from OP_RETURN
3. index runes based on OP_RETURN
4. inscribe runes to OP_RETURN
5. batch inscribes runes to OP_RETURN

I would like to know whether I can make reference to this [implementation](https://github.com/Anarkoic/runes/blob/main/runes.py)?

**Comment by winktool** [comment]
> I have completed the full function decipher and encipher using typescript, I will open source it soon, and maybe there will be another version using golang.

Any updates?

**Comment by lugondev** [comment]
I cannot make it open source right now. However, if you want to decode op scripts, I can provide you with the REST API to try. 
Sorry about the inconvenience.

**Comment by casey** [comment]
This is unlikely to happen before release, so I made an issue on ord: https://github.com/ordinals/ord/issues/3321
