### ISSUE TITLE
Find a good chinese name

### ISSUE THREAD

**Issue by casey** [casey/runestone#144]
The term "盧恩" is usually used in Mandarin Chinese for "rune". We could use this, or we could come up with a homophone, with one or both of the two characters replaced with another with the same sound.

**Comment by winktool** [comment]
乐印

**Comment by AlexV525** [comment]
> The term "盧恩" is usually used in Mandarin Chinese for "rune".

"rune" also means "符文" nowadays. "符文" is usually used as a combination of properties and abilities in the game "League of Legends"

**Comment by Rock-520** [comment]
I think that  "rune" is good name for Chinese , becuase  rune  is easy to pronounce and we  used to say “符文”  instead of "rune".

**Comment by arronzhang** [comment]
In the Chinese community, inscription is called 铭文. rune has also been called 符文.

**Comment by ylsGit** [comment]
I think "秘符" is very appropriate for a rune that contains a secret message, because the rune is encrypted.  Or "密令"

**Comment by wwens** [comment]
I think "符石" is cool.

**Comment by hsxyl** [comment]
A [poll](https://twitter.com/RunesCC/status/1754114925688168516) was conducted on Twitter, and the "符文" received all the votes.

**Comment by casey** [comment]
Thanks for all the input! Look forward to the chinese docs!
