### ISSUE TITLE
Consider switching to byte string encoding

### ISSUE THREAD

**Issue by casey** [casey/runestone#148]
Byte strings would allow additional flexibility, for example, values greater than 128 bits.

Some encoding like:

- 0..128 value is single byte with that value
- 128..255 value is next value - 128 bytes in length
- 255 next value is length, then byte string of that length is value

**Comment by summraznboi** [comment]
Can we have a decision here soon? This is blocking any third-party development of rune etchings/edicts on OP_RETURN.

**Comment by casey** [comment]
Thinking out loud:

What would be the benefit of byte strings? It would allow for tags which are either of arbitrary length, and the length is important, or tags which have length longer than 128 bits.

The only thing I've been able to come up with so far is a tag that specifies an alternative parent. However, since you're only worried about random collisions, you can encode the parent ID as the suffix of the inscription ID, and still have good collision resistance.

What else might you want to put in a runestone? I dunno, not much else I can think of. If you want big data in an etching, you should probably put that in the witness, since it's cheaper, and a commit is required in most cases anyways.

The varint encoding is very nice, since u128 is fixed size and copy, and many types can be natively converted to and from integers.

One major reason that I had was that I thought that it might be nice to have a byte-string encoding which would eventually be compatible with an alternative inscription encoding for putting in witnesses. But that's so far off that I don't think it's worth compromising the design of runes for.

So, I think we just stick with the varint encoding for now. However, for everyone watching this thread, this does not constitute a guarantee that this won't change before release. If I come up with a very compelling reason to do a byte-string encoding, I might change it.
