### ISSUE TITLE
Consider to restrict at least one of `Mint.deadline` or `Mint.term` not `None`?

### ISSUE THREAD

**Issue by zhiqiangxu** [casey/runestone#151]
Currently both `deadline` and `term` of [`Mint` ](https://github.com/ordinals/ord/blob/416b286759e2d8b985cefed4d0bd21b91942e266/src/runes/mint.rs#L4) can be `None`, which means it can be minted forever, such assets are not gonna be rare.

**Comment by raphjaph** [comment]
Yes, that's by design. The protocol allows everything. The issuer can restrict and make rare.

**Comment by HubertusVIE** [comment]
Daueremission. Makes sense for certain real economy applications.

**Comment by casey** [comment]
This is correct, if you want a rare rune, make sure to set deadline, mint, or term!
