### ISSUE TITLE
Proposal to treat burns similar to claims

### ISSUE THREAD

**Issue by wagmiwiz** [casey/runestone#152]
Right now rune burns are behind an etching flag. Is there a reason we couldn't do burns the same way as claims (via a bit mask of the rune id in the edict?). Conceptually it feels strange they are done differently.

So for example I could have an input with 100 of rune A. First edict could do a transfer of 50 and second edict could do a burn of 50 (output field is ignored).

**Comment by casey** [comment]
The etching flag turns the transaction into a burn transaction, which burns all inputs. You can easily actually burn runes more granularly by just using an edict to assign them to the OP_RETURN output.
