### ISSUE TITLE
Supply should be reduced after burns

### ISSUE THREAD

**Issue by wagmiwiz** [casey/runestone#153]
When processing burns should supply not be reduced at the same time as `burned` is incremented?

https://github.com/ordinals/ord/blob/master/src/index/updater/rune_updater.rs#L408

**Comment by casey** [comment]
I think you want to know the maximum supply there ever was, vs the current supply. We should tweak the terminology and how it's displayed:

- minted: total number of runes ever created
- burned: total number of runes burned
- supply: minted - burned

**Comment by casey** [comment]
We should also display the maximum supply. The maximum supply, before it's minted out, is the maximum possible supply, i.e., the premine + maximum mint count * mint limit. Once it's no longer mintable, then the maximum supply is the actual supply, i.e., premine + actual mint count * mint limit.
