### ISSUE TITLE
Come up with TXID-based rune ID

### ISSUE THREAD

**Issue by casey** [casey/runestone#154]
Something like rTXID: `r0902066c0fc20c24a92549f016ebc1d7939a0679644cd6b3ba4ff97806279c1e`.

**Comment by raphjaph** [comment]
There could be multiple etching per transaction though

**Comment by casey** [comment]
There can actually only be one etching per transaction.

**Comment by raphjaph** [comment]
Ah I see. I have to page the runes stuff back into my mind. Is this because of technical reasons or could it theoretically be done?

**Comment by casey** [comment]
No particular technical reasons, we could allow multiple etchings per transaction, but since I think that creating runes will be relatively rare (vs creating inscriptions) one per transaction is enough.

**Comment by raphjaph** [comment]
Yeah let's keep it that way. We have to make sure to clearly solidfy that in the documentation because the IDs will have to stay unique

**Comment by casey** [comment]
I think having two types of rune ID is probably confusing. If we come up with a compelling use-case, we can revisit this.
