### ISSUE TITLE
TODO: Select Activation Blockheight

### ISSUE THREAD

**Issue by Psifour** [casey/runestone#16]
"Decide on an activation height. The degens will surely REEEEEE loudly if there are any shenanigans around launch of the protocol. The best way to avoid this is to define an activation height well into the future."

**Comment by summraznboi** [comment]
I like this, not only to avoid handling the noise that is being generated now, but also so that indexers don't need to arbitrarily start indexer from the beginning when in practice there's nothing there anyways.

**Comment by elocremarc** [comment]
Wouldn't that put pressure on getting it done? Maybe it could be stated clearly there will be one then say TBD until its in a good phase to determine one for people to build on it.

**Comment by elocremarc** [comment]
Maybe start with a testnet activation first as well before mainnet

**Comment by stet** [comment]
halloween

**Comment by Psifour** [comment]
> Maybe start with a testnet activation first as well before mainnet

I fully support a testnet option, but is is implied in the Todo section of the readme that we can use "RUNE_TEST" for testing until said blockheight.

**Comment by owenstrevor** [comment]
This feels a little too dictator-esque. Is there a happy medium here where all the stuff before the blockheight is grandfathered in and then the protocol locks in after that blockheight?

**Comment by cbspears** [comment]
Given the Runic nomenclature I would explore "mystical" numbers, like 818,181 / 888,888 / etc.

October 31, Halloween and Whitepaper Day (Bitcoin's "Immaculate Conception") is perfect thematically but IMO too soon.

A block on Jan 3, 2024 (Bitcoin 15 year + Proof of Keys day) would be fun.

Alternatively, Block 840,000 seems reasonably far in the future as well as historic. It's also so far away as to antagonize speculators (who will have round tripped the entire Runecycle by then)

**Comment by BitTogether** [comment]
This sounds great! and people creating prototype runes can use airdrops of the runestone variety to relaunch any token made on prototypical rune styles before the activation height.  Perhaps the indexer of runes should have an option to index runes made before the block activation height just to make the pre-activation runes compatible with the post-activation runes for people who want to track pre-launch holders and airdrop to them post-launch.  We can give them negative inscription numbers and call them cu- wait... fuck no, nvm.  Sorry.

**Comment by summraznboi** [comment]
Another middle ground would be to finalize the RUNE_TEST to an unused value agreed by community after the protocol reaches stability. Technically then it isn’t an arbitrary block height activation, and could in theory grandfather anything in the past if there is any valid protocol messages in the past.

**Comment by hantuzun** [comment]
There're two options ahead:

**- Without activation blockheight:** The protocol development begins with a blog post, and there are different interpretations of this post. Some technically savvy individuals benefit from "ticker squatting" by correctly predicting the ticker encoding.
**- With activation blockheight:** The protocol's author determines its legitimacy after a specific block height. At this point, "ticker squatting" will involve among miners, those who bribe miners, those who fought fee wars on other chains etc.

In my opinion, the first option is the more decentralized one.

**Comment by cbspears** [comment]
> There're two options ahead:
> 
> **- Without activation blockheight:** The protocol development begins with a blog post, and there are different interpretations of this post. Some technically savvy individuals benefit from "ticker squatting" by correctly predicting the ticker encoding. **- With activation blockheight:** The protocol's author determines its legitimacy after a specific block height. At this point, "ticker squatting" will involve among miners, those who bribe miners, those who fought fee wars on other chains etc.
> 
> In my opinion, the first option is the more decentralized one.

This may be a very dumb idea but we could have a middle ground to combine the declining ticker length rule with the activation block height. Assuming shorter tickers are the most incentivized to frontrun, we could have a declining ticker length where we recognize declining lengths at certain blockheights.

I don't think this solves either problem very well, but I'm doing some back-of-the-napkin cost estimation of how much BTC it would take to frontrun the entire 3 & 4 length ticker set and it's quite low, so the cost of speculative frontrunning doesn't appear very prohibitive.

**Comment by jerryfane** [comment]
> > There're two options ahead:
> > **- Without activation blockheight:** The protocol development begins with a blog post, and there are different interpretations of this post. Some technically savvy individuals benefit from "ticker squatting" by correctly predicting the ticker encoding. **- With activation blockheight:** The protocol's author determines its legitimacy after a specific block height. At this point, "ticker squatting" will involve among miners, those who bribe miners, those who fought fee wars on other chains etc.
> > In my opinion, the first option is the more decentralized one.
> 
> This may be a very dumb idea but we could have a middle ground to combine the declining ticker length rule with the activation block height. Assuming shorter tickers are the most incentivized to frontrun, we could have a declining ticker length where we recognize declining lengths at certain blockheights.
> 
> I don't think this solves either problem very well, but I'm doing some back-of-the-napkin cost estimation of how much BTC it would take to frontrun the entire 3 & 4 length ticker set and it's quite low, so the cost of speculative frontrunning doesn't appear very prohibitive.

What if we allow duplicate symbols https://github.com/casey/runestone/issues/5 we don't even have to think about these cases.

**Comment by cbspears** [comment]
> What if we allow duplicate symbols #5 we don't even have to think about these cases.

Yeah interesting consideration.

**Comment by casey** [comment]
Deciding on a block height in advance would put  pressure on completing the implementation quickly. So, I propose this:

- The activation height is initially un-announced.
- When the implementation is complete we will announce the activation height.
- When it is announced, it will be at least 2016 blocks (144 * 14, the length of a difficulty adjustment) in the future.
- It will fall on a difficulty adjustment, since that seems more auspicious.
- This gives everyone a fortnight to prepare.

All of this applies to the *this implementation only*. I don't presume to speak for anyone else, or be able to control what anyone else does. People are free to create competing implementations and specs with whatever activation method they prefer. My goal, if I finish this implementation (see issue #3) is to produce a high quality implementation with fair rules and a good spec, which becomes the dominant implementation *because it is the best*.

**Comment by Psifour** [comment]
>     * When it is announced, it will be at least 2016 blocks (144 * 14, the length of a difficulty adjustment) in the future.

I'm gonna need a minimum of 2 months. :laughing: 

Kidding aside, I think that putting a deadline on development is suboptimal, I agree with having a minimum time period after the initial specification is live. The other factors don't really apply to me, but aligning to a difficulty adjustment seems to have no drawbacks and may actually increase the buffer period by up to 2015 blocks (worst case scenario).

**Comment by casey** [comment]
Closing in favor of combined block height and payload signature issue #59.
