### ISSUE TITLE
Genesis runes

### ISSUE THREAD

**Issue by casey** [casey/runestone#160]

**Comment by rishabhjava** [comment]
If I understood from the podcast correctly, you will be pre-inscribing 10 runes as you don't want people to decide what the first 10 runes they will come into existence at a specific blockheight, what's that blockheight going to be?

**Comment by lopezi** [comment]
>  also you say they will come into existence at a specific blockheight, what's that blockheight going to be?

<img width="609" alt="Screen Shot 2024-03-04 at 12 02 02" src="https://github.com/casey/runestone/assets/388476/45b8d5d1-4595-468d-bade-4d0cf4034ec4">

**Comment by Shaifff** [comment]
If you don't call the first rune Valhalla, I'm going to be so damn upset, idc how much I get if I can just get some from the initiation txn to bc1pu3vgxjh9yf4upzhhhct06d8v9ka6xqa8y0s2d8yfpr2zhm5s4l8se6x672 :3

**Comment by Shaifff** [comment]
if you dont name the first rune Valhalla it'll be such a fumble for the 10 genesis

**Comment by alexluffy** [comment]
The community will decide on the first 10 runes.

**Comment by onepixelinscriptions** [comment]
These first 10 runes, are they going to be free mints or minted 100% by Casey and then distributed?
