### ISSUE TITLE
Decide whether or not to forbid weird encodings

### ISSUE THREAD

**Issue by casey** [casey/runestone#163]
This includes:
- Overlong integers
- Overlong bytestrings (if we use the overlong bytestring encoding)
- On-ordered fields
- Duplicate fields
- etc.

On the one hand, these things are just weird and shouldn't be done. On the other hand, I *think* that the overall effect is to make the code more complex. And if we miss a weird encoding that we forbid, we can't add it later without some difficulty.

**Comment by summraznboi** [comment]
I personally like the current format, it keeps the parser simple, and those edge cases are exceptional and only used in practice in attempts to break the protocol.

**Comment by casey** [comment]
We've made a bunch of things stricter. For example, the varint encoding is simpler but less permissive, and many things produce a cenotaph now. Field order and duplicate fields are still allowed.

@summraznboi I changed the varint encoding to be a standard LEB128. I don't plan on changing the varint encoding again before launch.

**Comment by summraznboi** [comment]
Thanks for the heads up @casey!
