### ISSUE TITLE
Multi-UTXO Chain Extension for Runes?

### ISSUE THREAD

**Issue by xcshuan** [casey/runestone#167]
The way Runes issues assets makes it convenient for SPV nodes to index, which will provide Runes with features that BRC20 does not have. For example, implementing BTC's SPV node on a blockchain would allow that blockchain to serve as a decentralized indexer for Runes.

Additionally, is it possible for Runes to circulate across multiple UTXO chains?

Runes is a UTXO-based asset protocol, where a UTXO can be identified by (txHash, out_index), a BTC UTXO. Perhaps a chain_id allocation mechanism can be added to the Runes protocol to assign chain_ids to UTXOs. This way, a UTXO can be uniquely located globally by (chain_id, txHash, out_index).

Maybe a special type of transfer transaction can be defined, where instead of transferring assets to an output UTXO, it transfers to an identifier (chain_id, txHash, out_index), indicating the assets are transferred to a UTXO on the UTXO chain corresponding to chain_id. This could be implemented as an extension plugin for the indexer.

So what kind of UTXO chains could be integrated into the indexer?

First, it should have an extremely lightweight light-client, such as [Non-Interactive Proofs of Proof-of-Work](https://eprint.iacr.org/2017/963) or [Flyclient: Super-Light Clients for Cryptocurrencies](https://eprint.iacr.org/2019/226). UTXO chains with NIPOPOW and Flyclient can be very lightly integrated to the indexer. By defining an abstract light client interface, different UTXO chains can be integrated using different implementation.

Second, since different UTXO chains may differ in UTXO design, the module for parsing transactions to Runes operation should also be abstracted as an interface, so that different UTXO chains can implement their own.

In this way, with Runes as the intermediary and BTC at the core, many UTXO chains can be connected to form a multi-chain UTXO network. Using a mechanism similar to RGB's  [xchain](https://github.com/RGB-WG/rgb-core/blob/v0.11/src/contract/xchain.rs), Runes assets can circulate across different UTXO chains without cross-chain bridges, which is more secure compared to the EVM ecosystem interconnected by cross-chain bridges.

Supporting UTXO concatenation brings benefits to Runes and BTC:

+ Issuing assets on BTC will gain more consensus among users, while asset circulation can happen on other UTXO chains. This will greatly save space on the BTC chain and allow Runes users to operate Runes assets with lower fees and faster settlement.
+ Runes is positioned as an asset issuance protocol without smart contract functionality. However, if Runes supports asset circulation on other UTXO chains with Turing-complete script, like eUTXO, then Runes effectively gains smart contract capabilities, enabling native  DeFi protocols.
+ By connecting multiple UTXO chains to BTC through the Runes protocol, then Runes, as the first asset protocol connecting all UTXO chains, will have its position in the BTC ecosystem defended and solidified.

Further, is it possible for Runes to combine with the Lightning Network, thereby further expanding its capabilities?

**Comment by casey** [comment]
> Additionally, is it possible for Runes to circulate across multiple UTXO chains?

Runes will be Bitcoin-only. If people want to support different chains, they are free to fork the code.

> Maybe a special type of transfer transaction can be defined, where instead of transferring assets to an output UTXO, it transfers to an identifier (chain_id, txHash, out_index), indicating the assets are transferred to a UTXO on the UTXO chain corresponding to chain_id. This could be implemented as an extension plugin for the indexer.

This would introduce enormous, crushing complexity to verification. To verify that a transfer of runes was valid, you would have to follow the history of those runes across multiple chains, which would include verifying transactions of those other chains. This is a non-starter.

> First, it should have an extremely lightweight light-client, such as [Non-Interactive Proofs of Proof-of-Work](https://eprint.iacr.org/2017/963) or [Flyclient: Super-Light Clients for Cryptocurrencies](https://eprint.iacr.org/2019/226). UTXO chains with NIPOPOW and Flyclient can be very lightly integrated to the indexer. By defining an abstract light client interface, different UTXO chains can be integrated using different implementation.

Bitcoin SPV clients are already light enough to run on phones, so I don't think there's much advantage to more complex schemes.

> Further, is it possible for Runes to combine with the Lightning Network, thereby further expanding its capabilities?

Lifting runes onto the lightning network is definitely possible.

**Comment by xcshuan** [comment]
> Runes will be Bitcoin-only. If people want to support different chains, they are free to fork the code.

Ok, I see.

> This would introduce enormous, crushing complexity to verification. To verify that a transfer of runes was valid, you would have to follow the history of those runes across multiple chains, which would include verifying transactions of those other chains. This is a non-starter.

Under this architecture, the Indexer does not need to verify transactions from other chains. It can draw inspiration from the Hub architecture, where the Indexer acts as a Hub, owning light nodes of other UTXO chains without syncing any transactions. 

For each chain, there is a Relayer responsible for relaying Runes transactions occurring on its chain to the indexer. The Indexer can use the light nodes to simply determine whether a transaction is valid and parse it. Since the Relayer relays all valid transactions to the Indexer, the Indexer has a localized UTXO history sequence for Runes assets specific to that chain, making verification straightforward.

![image](https://github.com/casey/runestone/assets/24284441/0432948d-6234-4b23-93d0-c2d4edb39e91)

However, considering that Runes' current goal is to be a BTC-only protocol, and it might be too early to design such an extension at this stage. Thank you for your reply.
