### ISSUE TITLE
Rune Etch, Mint, Limit Questions

### ISSUE THREAD

**Issue by bensig** [casey/runestone#169]
`ord wallet etch` works to "deploy" a rune - but then how does one claim or mint a rune? 

How does one set limit, deadline and term? 

How do edicts work? 

What is the plan for preventing (or making it harder) to frontrun rune etching?

I have read through the `ordinals/ord` repo and a few of the issues here dealing with concepts such as "mint period" and "fair launch" vs "full mint" - but I don't see a way to mint implemented in `ord` CLI yet...

**Comment by casey** [comment]
> `ord wallet etch` works to "deploy" a rune - but then how does one claim or mint a rune?

`ord wallet etch` has been removed, now runes are etched with `ord wallet inscribe --batch`.

> How does one set limit, deadline and term?

These can be configured in the batchfile.

> How do edicts work?

Edicts mostly can be ignored by users. They are an implementation details. You can do `ord wallet mint` to mint a rune, which will create the etchings for you.

> What is the plan for preventing (or making it harder) to frontrun rune etching?

This has been added! We use a commit/reveal scheme.

> I have read through the `ordinals/ord` repo and a few of the issues here dealing with concepts such as "mint period" and "fair launch" vs "full mint" - but I don't see a way to mint implemented in `ord` CLI yet...

This has been implemented now.
