### ISSUE TITLE
Should rune commitment be required to be equal to commitment, or just start with commitment?

### ISSUE THREAD

**Issue by casey** [casey/runestone#172]

**Comment by victorkirov** [comment]
Just dumping a thought on this.

The commitment is effectively committing to the hex value of the number. As the number grows, the associated name would change.

e.g. 0x016097d0d1a143d6 => AAAAAAAAAAAAA
Adding a new least significant byte would result in a number that matches the start of the commitment but results in a completely different name:
0x01016097d0d1a143d6 => GLHXCZMXSYUMQU

Maybe there is another use case though?

Also, an issue with this is that someone could do a commitment to 0xd6 and be able to front run any rune starting with that commitment byte unless there are further limitations and restrictions as to what you can commit to.

**Comment by casey** [comment]
Thinking out loud here:

If the commitment merely has to start with the rune commitment, then you can include additional bytes in the input. This is useful if you want a blinding factor, since otherwise, your

**Comment by casey** [comment]
I think we shouldn't do this. I was thinking:

- Maybe you also want to include a nonce, and you can do that in the commitment data push, if the commitment only has to start with the commitment. However, you can do that in other ways.

- Maybe you want to store other data in the commitment. However, there's no guarantee there won't be multiple data pushes that start with the commitment, so this would be unreliable if you need to be able to extract that data.
