### ISSUE TITLE
Reserve tag ranges for custom extensions

### ISSUE THREAD

**Issue by summraznboi** [casey/runestone#175]
For support of future metaprotocols, I propose reserving the tag ranges 100-125 for custom metaprotocol/extension usage, with tag 100 being the metaprotocol identifier. No code change is even really needed, over than potentially reserving them in the unused section like the Burn and Nop tags currently; what's more important is calling it out in any future protocol documentation. We would require that these extensions follow a basic pattern, such as keeping edict rules the same and keeping balances in utxos.

**Comment by casey** [comment]
`ord` treats runestones with unrecognized even tags as burning all of their input runes, and burning any rune being etched. If someone creates a modified client that gives meaning to an unrecognized even tag, that will not be a metaprotocol or extension, but an entirely different an incompatible protocol. This is in contrast to inscription metaprotocols, which are valid inscriptions, and use data without protocol semantics, i.e., the inscription body, for protocol messages.

So, my stance is that all even tags are reserved for use by the protocol, and that anyone who wants to create a modified protocol that would require a new even tag or different semantics for existing even tags should use a different protocol identifier. (Currently `RUNE_TEST`, but will be change before launch.)

Odd tags can be more flexible, but from experience with inscriptions, I think the best policy is to also keep all odd tags reserved for the protocol, and try to be more responsive to user needs in allocating them. I don't know of many uses of odd inscription fields which weren't better served by something later delivered by ord itself.
