### ISSUE TITLE
Benchmark index with and without rune index

### ISSUE THREAD

**Issue by casey** [casey/runestone#193]

**Comment by emilcondrea** [comment]
As of curiosity I did a benchmark few days ago, before and after changing protocol discovery from RUNE_TEST to PUSH_NUM_13 (same flags --index-runes). 

For indexing testnet, 
* before: 8minutes 31 seconds
* after 13minutes 41 seconds

**Comment by casey** [comment]
Was this just with that single change, or were there multiple related changes being benchmarked? A bunch of things have been changing, so it's possible it was something else that slowed it down.

**Comment by emilcondrea** [comment]
A single change, I tested the exact 2 consecutive commits:

https://github.com/ordinals/ord/commit/d141f4735d0b395cdfb13bf49f5d55e69a0ab7e7
https://github.com/ordinals/ord/commit/800d447fb24dbb5075db741d982aef6413b5f8be

I think there could be many collisions on the new protocol tag with other opreturns.

**Comment by emilcondrea** [comment]
I have the results saved in a notes file:
The index directories were empty, so started from scratch. I only added --index-runes flag

```
 ord git:(800d447f) ✗ time ./target/release/ord --testnet --index-runes --data-dir ./index7-prev  index update
./target/release/ord --testnet --index-runes --data-dir ./index7-prev index update  258.71s user 58.45s system 62% cpu 8:31.21 total

----
 ord git:(d141f473) ✗ time ./target/release/ord --testnet --index-runes --data-dir ./index7-new-2   index update 
./target/release/ord --testnet --index-runes --data-dir ./index7-new-2 index   392.71s user 127.54s system 62% cpu 13:46.80 total

```

**Comment by raphjaph** [comment]
Excellent find! We'll probably try to use a multi-byte OP_CODE that doesn't conflict with others.

**Comment by emilcondrea** [comment]
There are probably multiple things slowing the indexer, here is a fresh run on todays testnet, latest master ord commit: https://github.com/ordinals/ord/commit/d6d8f70f85eea8920d33fabd3765c9e6e0f7cf0c

The last ~15k blocks were indexed the slowest.

```
➜  ord git:(master) ✗ time ./target/release/ord --testnet --index-runes --data-dir ./index11   index update 
./target/release/ord --testnet --index-runes --data-dir ./index11 index update  434.52s user 171.85s system 47% cpu 21:06.14 total
```

**Comment by raphjaph** [comment]
yeah for sure. At the moment we're locking down error paths and changing the encoding, once we're finished with that we'll try to optimize.

btw, you can also not index inscriptions by passing in the `--no-index-inscriptions` flag. Haven't tested it with `--index-runes` together so not sure if it'll work but try it out if you want.

**Comment by casey** [comment]
I'm going to search existing mainnet OP_RETURNs for the shortest minimally ambiguous prefix.

**Comment by casey** [comment]
I searched mainnet, testnet, and signet OP_RETURNs for `OP_RETURN OP_PUSHNUM_13`, and found very few instances, so I don't think that collisions are the issue here.
