### ISSUE TITLE
Allocate input runes evenly to outputs

### ISSUE THREAD

**Issue by casey** [casey/runestone#20]
For a transaction with N outputs, given a transfer of `[ID, AMOUNT, N]` and M non OP_RETURN outputs, each non OP_RETURN output receives `AMOUNT / M` runes.

This allows evenly distributing runes to a large number of outputs, without having include a transfer in the runestone for each output.

**Comment by summraznboi** [comment]
Nice, I like it! The only concern with `AMOUNT / M` is how to handle it when it’s not evenly divisible. I assume the most obvious solution is to distribute the modulo M amount from first output onwards until done.

**Comment by owenstrevor** [comment]
Apologies in advance: this comment doesn't have any content.

Just want to say, LFG!!!

**Comment by casey** [comment]
> Nice, I like it! The only concern with `AMOUNT / M` is how to handle it when it’s not evenly divisible. I assume the most obvious solution is to distribute the modulo M amount from first output onwards until done.

There's already the property that any un-assigned runes are assigned to the first non OP_RETURN output. So each output could get `floor(AMOUNT / M)`, and if M doesn't divide amount, those unassigned runes go to the first non-op return.
