### ISSUE TITLE
The Wacky Zone

### ISSUE THREAD

**Issue by casey** [casey/runestone#26]
What are some wacky mechanics that runes might support? Crazy ideas welcome.

Some ideas:

- Gambling. The result of a transaction depends on the hash of the block it is included in. So you can make a transaction which assigns runes to either the first or second output, and you don't know which output the runs are assigned to until the transaction is mined. Opens the door to MEV, so maybe not worth it. Some way of putting in a vig, i.e., a house edge, would be good, so people are incentivized to run literal shitcoin casinos.

- Air drops. Right now, I think the best way to do this is with the ability to distribute tokens to outputs evenly. If this were combined with OP_CTV, you could create large fan out transactions, ending in a large number of anyone can spend outputs with an even number of tokens, with the cost of minting fully pushed to minters, since they need to pay the fees to splay out the tree of transactions to get to the anyone-can-spend outputs. This can be done without OP_CTV, but in this case the cost of issuing is on the issuer.

- Some kind of efficient market making mechanic. Of course, you can create a whole bunch of PSBTs for different lot sizes, and maybe that's the best option. However, there could also be a mode where you put in X amount of rune Y, define a Y/BTC exchange ratio, and then the market taker puts in their own BTC input, and the tokens in the outputs are distributed according to how much BTC they put in. This would avoid a proliferation of PSBTs.

- Yield. People love fucking yield, and they love shitcoin yield. One fundamentally hard part of yield is that you get more of the token than you put in. I guess a rune could have an additional parameter which states, if you don't move the runes for a particular amount of time, an interest rate, and you get more runes out when you eventually spend the UTXO. This has weird interactions with supply, and with a capped supply. I guess yield could come from whatever the un-allocated initial supply was. So you can run out of the source of yield if you yield out the full amount of the initial un-allocated supply.

- Ponzi schemes. People fucking love ponzi schemes. I guess ponzi schemes are a form of yield where getting the yield isn't guaranteed. So it might emerge naturally from the above yield scheme, where you have a pool of coins you can get yield from, but when they're gone, they're gone, so if you're the last to move your coins, you only get what you put in, which is now worth dramatically less. Or maybe, it's a yield scheme, where the yield is taken out of the actual supply, so you might not get what you put in after a while.

- Demmurage. Some people are insane about demmurage, and think it solves all kinds of problems. This could easily be implemented, with runes decaying according to some formula the longer they don't move. Let the wacky socialists have their weird demmurage experiments.

**Comment by HYAIPE** [comment]
#based

**Comment by owenstrevor** [comment]
Let's get wacky!

I like the even airdrops because of it's efficiency, it's a great solution for that. Also, it makes indexing much easier by being able to identify airdrops in blocks. If it is possible (other than through normal tx method), I still think it makes sense to have an idea for airdrops that are not even, considering most airdrops are done by snapshots of token holdings or other user metric. For example, an Ordinals PFP project may want to airdrop a loyalty or voting token proportionally to the holder base. In all the popular projects, there are many people who hold different amounts of those PFPs. e.g. there are people who have 100 DeGods, 2, 3, 4, 5, etc. and a spendable voting token might airdrop 1 token for each 1 DeGod for every new voting proposal. I suppose worst case scenario, holders could spread each of their DeGods out to unique wallets, but then it will be harder to have special gated chat rooms where you authenticate the # of DeGods in a wallet, e.g. a chat channel for holders with 10+ DeGods.

**Comment by utxo-detective** [comment]
Taxation. Any psbt swap of a rune could account for capital gains and automatically move token balances into addresses owned by the IRS. The time saved by this automation would save many billions of taxpayer dollars and allow degens to focus more on what they do best

**Comment by samsagewize** [comment]
My two sats is that it's hard to call the market sometimes, let the market build with you and mistakes like BRC-20 have room to grow and stay, imperfection sometimes is good! Im open to support all #bitcoin Protocols

And you always say they, what do YOU like? i think you should trust your gut, we really have grown as a community and appreciate the wisdom!! Much love Casey!

**Comment by ordinalOS** [comment]
**1. Self-destructing Tokens:** Set lifespan and will automatically be destroyed after certain block height, or diminish in circulation over time.

**2. Difficulty Pegged Tokens:** The value or behavior of the token is pegged to the mining difficulty. 

**2.1 Difficulty Futures:** Tokens that represent bets on future block difficulty. 

**2.2 Block Height Bonds**: Pay out or mature at a specific block height.

**2.3 Height-based Token Birth:** New tokens are minted or born at specific block heights

**3. Block Height Rewards:** Special rewards or token behaviors are triggered at certain block height.

**3.5 Height-locked Tokens:** Tokens that are locked until a specific block height is reached.

**4. Difficulty Multiplier:** Difficulty of a block can determine the multiplier.

**5. Token Fusion:** Two different types of tokens can be combined to create a third.

**6. Dream Tokens:** Tokens that "wake up" reverting to their original state, making all transactions null and void.

**7. Emoji / Unicode Tokens:** Allow pictorial symbols and universal character sets!! (please)

**8. Inscribe rune graphics in witness data:** Sucks if permanent but interesting idea

**Comment by TANGX2021** [comment]
it must be Gold in it

**Comment by owenstrevor** [comment]
Trying to throw a challenge out here based on Counterparty. I don't think these are possible without an account-based model though.

**Dispensers**

> A common way to buy and sell assets on Counterparty is through automated dispensers. Similar to vending machines, anyone can set up a dispenser and specify an amount of the token or asset they want to sell through it, along with the price in BTC or Counterparty's own XCP token.
>Buying assets from dispensers is not all that different from transferring or sending tokens between wallets. All a buyer needs to do is scan the dispenser QR barcode or manually copy the dispenser wallet address, and then send the amount of BTC or XCP they want to spend to buy one or more of the items on offer. Upon receipt, the dispenser will then distribute the asset to the buyer's wallet.
> Another way to think about dispensers is as a basic smart contract with predefined rules that autonomously distribute and manage its assets. To help mitigate any risk or scams, an empty dispenser will display a warning sign alongside it, telling buyers not to send any BTC as the dispenser is closed.

Perhaps this could be done in the future with OP_CTV?

**Comment by elocremarc** [comment]
What about bonding curves for distribution?

**Comment by casey** [comment]
I should add, I won't add anything that is a potential MEV vector, which precludes a lot of this stuff, as fun as it is.

**Comment by jerryfane** [comment]
Deflationary transaction based fee token: implement a transaction fee token model. Each token transaction includes a x% fee. Fees can be re-distribute to any other pre-defined address (eg. Team, Pool, burn address) and it can implement a de-facto deflationary token. Great for degens

**Comment by casey** [comment]
Distribution via burn: after creation, some amount of un-allocated coins can be claimed by burning sats. Can be boxed to a certain block height after creation. (Credit to [windsock on twitter](https://twitter.com/windsok/status/1709819563670712350).)

Note to self: One thing I dislike about BRC-20 style airdrops is that they aren't amenable to SPV proofs. E.g, you have to see every single transaction to know whether or not a mint transaction is valid. However, with burns that are limited to a block height, if the restriction is in place that even if every single sat is burned, you won't overflow the token maximum value, then you know that every single burn within a block range is valid, even if you don't see every single transaction.

You could support BRC-20 style airdrops that didn't require a burn if you ensured that even if every single transaction was a BRC-20 airdrop, it wouldn't overflow the max token value. This would require bounding by height, or by using such a low value that even if every transaction was a mint, until the end of time, you wouldn't overflow the token max value.

**Comment by casey** [comment]
I think most of this stuff either can't be done, or would introduce MEV. I created #58, #54, and #55 for the feasible stuff.
