### ISSUE TITLE
Consider renaming Rune ID to Rune Pointer

### ISSUE THREAD

**Issue by casey** [casey/runestone#33]
Current rune IDs are a combination of block height and transaction offset. IDs are usually hashes, and we may want to refer to the txid of the transaction in which a rune is created as the "rune ID". Perhaps Rune ID should instead be called something like "rune pointer", so we can have both concepts.

**Comment by stet** [comment]
rune location?

**Comment by casey** [comment]
I think that would be confusing, since I would think of the location of a rune as being the outputs which currently have a non-zero output of the rune.

**Comment by casey** [comment]
Another idea is "slot". I've used the word "slot" to refer to some combination of block height / transaction index / output index, but it's not a common use.

**Comment by stet** [comment]
> I think that would be confusing, since I would think of the location of a rune as being the outputs which currently have a non-zero output of the rune.

Gotcha. Internally on my end, I refer to tx as location and output indices as positions.

**Comment by summraznboi** [comment]
Question, did we ever agree on whether runestones in multiple OP_RETURNs of a nonstandard transaction are allowed or not? If not, what's the expected behavior to resolve two different runestones? (First one in output order, or both invalid?)

**Comment by summraznboi** [comment]
Also, other names to "rune pointer" are:
- rune reference
- rune handle
- rune descriptor
- issuance ID
- rune birthday (works well with #35 with `BLOCK/TX` as some sort of date looking string)

**Comment by casey** [comment]
I think Rune ID is okay for now.
