### ISSUE TITLE
Allow issuance to not specify rune, and receive shortest available rune?

### ISSUE THREAD

**Issue by casey** [casey/runestone#34]
A naive implementation would have to iterate backwards over the rune table every time an issuance didn't specify a rune.

A more sophisticated implementation would have to maintain a table of ranges of unallocated runes, and split/shrink them when a rune is allocated, and remove ranges when the last rune is allocated in a range.

**Comment by summraznboi** [comment]
Should it be the shortest available rune? If issuance didn't specify a rune, its likely that they aren't interested in the rune symbol to begin with, so perhaps giving them the longest available rune makes more sense.

**Comment by casey** [comment]
Currently, if you try to fool someone into accepting a mapping bad mapping from ID0 to RUNE, a full index can construct a fraud proof which shows that there was an earlier etching with ID1 which claimed RUNE, and thus ID0 can't have that rune. This does not prove that ID1 maps to RUNE, because there could have been an even earlier etching, but it does help.

With this feature, RUNE could have been claimed by an etching that did not specify the rune, and received RUNE because it was the shortest/longest available at the time.

So I don't think this is a good idea. Plus the implementation winds up being pretty complex.
