### ISSUE TITLE
Define text representation of rune id

### ISSUE THREAD

**Issue by casey** [casey/runestone#35]
- `BLOCK/TX` I like this, since it's similar to the familiar use of `/` in paths and URLs.
- `BLOCK.TX` This works, but it conflicts with `BLOCK.SAT` for ordinals
- `BLOCK-TX`

**Comment by summraznboi** [comment]
I agree, it also makes APIs more elegant, since you could in theory have just a `/BLOCK` view which shows you all runes issued in that block, and `/BLOCK/TX` view of just the issued rune.

**Comment by casey** [comment]
Done, using `BLOCK/TX`.
