### ISSUE TITLE
Consider an initial period on mainnet where nothing is guaranteed

### ISSUE THREAD

**Issue by casey** [casey/runestone#43]
I'm not sure about this, but something like an explicit 3-6 month period where, due to bugs in the protocol, we might have to change things in a way that nukes runes.

**Comment by summraznboi** [comment]
Call it the genesis period, and any runes that survive it has that attribute tied to it lol. Even more speculation during the transient period haha.

**Comment by casey** [comment]
On reflection, I don't think we should do this, especially if we use #51, which allows upgrades to the protocol.
