### ISSUE TITLE
Reconsider default divisibility

### ISSUE THREAD

**Issue by casey** [casey/runestone#48]
I think divisibility zero might be a better default. 18 is fine, but it could be unexpected.

**Comment by stet** [comment]
18 was pulled from ethereum to coincide with the borrowed and non-sensical name BRC-20.
Bitcoin is all about 8 dec so I encourage staying inline with Bitcoin if a default other than 0 (which I might prefer actually).

**Comment by casey** [comment]
Changed to 0, I think a zero default is just simpler conceptually.
