### ISSUE TITLE
Finalize varint implementation

### ISSUE THREAD

**Issue by casey** [casey/runestone#53]
- Do we want a varint implementation, or variable length byte strings? The latter could be advantageous if we want to have byte string fields that are not numbers.
- Should we use a bijective encoding? A bijective encoding makes test vectors more complex.
- Should we use something which is more efficient given that we know what the distribution of numbers is likely to be? E.g., encodes zero as less than a single byte, encodes the distribution more efficiently.

**Comment by summraznboi** [comment]
👍  for simpler varint, given that in practice there's only a 1/129 chance of saving a byte due to landing in between byte boundaries (if assuming uniform distribution - in practice it'll be much much less).

**Comment by casey** [comment]
If anyone knows a good way of encoding a sequence of byte strings, let me know.

**Comment by casey** [comment]
I'm considering an encoding where every value is a byte string. Single bytes with values < 224 are encoded as a single byte. Anything else is encoded using (first byte - 223) as the number of byes that follow.

**Comment by summraznboi** [comment]
What about we also use FF to denote second byte as number + 32 bytes to follow? Then that way we have future proofing of extending a byte string out to 287 bytes, or if we wanted maximal flexibility, FF denotes following bytes as varint which is number of bytes + 32 to follow as byte string.

**Comment by casey** [comment]
That's a possibility, although, given the small payload sizes, I'm not sure it's worth it. The maximum payload size of an OP_RETURN is 80 bytes, which is just 2.5 32 byte values. Although if the OP_RETURN size restriction were lifted (which might happen if runes get popular, incentivizing miners to lift the limit), then larger payloads might be used. However, reserving 0xFF is just one value. Instead of a varint, I would do 0xFF = next four bytes are length, 0xFE next 3 bytes are length, etc.
