### ISSUE TITLE
Variable offers

### ISSUE THREAD

**Issue by casey** [casey/runestone#58]
Some of this has been discussed in #46 and #21. 

Fixed offers are quite trivial, you put the runes you want to sell into a UTXO, then you sign a PSBT that spends that UTXO and pays you the sale price. The completed transaction looks like:

```
BTC_INPUT  | RUNE_OUTPUT
RUNE_INPUT | BTC_OUTPUT
```

However, that requires transferring a fixed number of runes for sale into UTXO. There should be some way of making a "variable offer", where you don't need to transfer runes to a separate UTXO.

I can't think of a way where a seller can commit to both a runestone and an output paying them BTC in a PSBT.

One idea is that you transfer some amount of runes in one step using a runestone that gives the exchange rate, and *then*, you use that UTXO as input to another transaction. However, you need to make sure the buyer can't do anything but supply btc and take their runes. So, for example, they can't insert their own runestone which modifies the transfer of runes.

**Comment by casey** [comment]
1. Seller creates an "offer" UTXO, which offers the runes in the UTXO for sale, encoding the terms of the offer into a runestone in the transaction which creates the "offer" UTXO.

2. Seller then creates a PSBT:

```
OFFER_UTXO | RUNE_CHANGE_TO_SELLER
```

3. Buyer completes the PSBT:

```
OFFER_UTXO     | RUNE_CHANGE_TO_SELLER
PURCHASE_PRICE | PURCHASE_PRICE_TO_SELLER
               | PURCHASED_RUNES_TO_BUYER
```

`PURCHASE_PRICE_TO_SELLER` is an output with the same script pubkey as `RUNE_CHANGE_TO_SELLER`.

`PURCHASED_RUNES_TO_BUYER` gets allocated runes according to the terms of the offer UTXO, and the amount of BTC in `PURCHASE_PRICE_TO_SELLER`.

Any runestone in the completed transaction must be ignored, since it could contain edicts which transfer all runes to the buyer.

**Comment by sondotpin** [comment]
We can use OP_CHECKLOCKTIMEVERIFY to specific seller to not cancel offer in a fixed time
```
OP_IF
    <locktime> OP_CHECKLOCKTIMEVERIFY OP_DROP
    <pubkey_for_seller_address> OP_CHECKSIG
OP_ELSE
    1 <pubkey_for_any_other_address> OP_CHECKSIG
OP_ENDIF
```

**Comment by casey** [comment]
If we want to get crazy, we can also allow rune / rune offers, where you can offer one rune in exchange for another. Would be quite complicated.

**Comment by summraznboi** [comment]
> Any runestone in the completed transaction must be ignored, since it could contain edicts which transfer all runes to the buyer.

We could make the general policy that any UTXO containing runes will only obey the first runestone that instructs it. Thus the offers UTXO has the exchange rate edict applied to it on UTXO creation, and so any later transactions that spends the offer UTXO cannot redefine the behavior of the runes with a runestone in the spending transaction.

**Comment by sondotpin** [comment]
with this design, still need SIGHASH_SINGLE | ANYONECANPAY? @casey

**Comment by casey** [comment]
Yup, that's correct. The seller signes their one input and one output with sighash single | anyone can pay.

**Comment by casey** [comment]
The seller should set the value of `RUNE_OUTPUT` slightly greater than `BTC_INPUT`, to make it costly for buyers to complete the transaction without buying any runes, which would cause the seller to have to recreate the transaction.

**Comment by casey** [comment]
Another note: When an offer is accepted, if there is a runestone, any etching, distribution of new tokens, and claims of open etchings still need to happen.

**Comment by casey** [comment]
```
To process an offer:

- Check if the first input is an offer UTXO
- If it is, than any edicts allocating input runes are ignored
- Get the address of output 1. This is the rune change output, to transfer un-sold runes back to the seller.
- Get the address of output 2. If this output does not have the address of the first output, this accept is invalid. Output 2 is created by the buyer, with the amount of BTC the buyer wishes to exchange for runes.
- Output 3 is where purchased runes go to the buyer.
- Get the amount of output 2, this the amount of BTC paid by the buyer.
- Assign purchased runes, according to the exchange rate stipulated by the seller for the offer UTXO, to the third output.
- All left over runes go to first output, which is the seller's, as per usual.
```

**Comment by AIRBLOOD** [comment]
> ```
> - get the value of the second input, this is the amount paid by the buyer
>   now, assign as many runes, according to the exchange rate stipulated by the buyer,
>   to the third output
> ```

@casey you mean "exchange rate stipulated by the **SELLER**", right? Or am I understanding it wrong?

**Comment by casey** [comment]
Good catch, I updated the comment to fix that, as well as just make it clearer in general.

**Comment by sondotpin** [comment]
this is demo of Variable Offer @casey 
Seller sell `100 AOPOO` for 5000 sats

<img width="1444" alt="Screen Shot 2023-10-25 at 12 07 11" src="https://github.com/casey/runestone/assets/49492179/fee00abb-45f0-4712-874d-e8929150df5b">

https://mempool.space/testnet/tx/aa981a0ac0278405e28a965675b2d2f222e19381a78c16d2d55f22d1c8da6c01

**Comment by myfirst-crypto** [comment]
hi brother, this pic is wonderful, it could show the rune coin flow(1000->900+100), could you please share the website/url  with me? thank you  so much! @sondotpin

**Comment by sondotpin** [comment]
I think we should discuss about technical here. everything other could dm my twitter (alias at my github)

**Comment by casey** [comment]
I think this is very far into the future, and I'm not sure this is the best way to support variable offers. My current line of thought is that, on bitcoin, the best way to have liquidity pools and AMMs, is actually to have online nodes which can collaboratively construct atomic swap transactions with any terms. I'm thinking of calling this approach "light pools". Look forward to a blog post!
