### ISSUE TITLE
Finalize activation parameters

### ISSUE THREAD

**Issue by casey** [casey/runestone#59]
This includes an activation block height, as well as finalizing the runestone signature.

Activation height:
- The activation height is initially un-announced.
- When the implementation is complete we will announce the activation height.
- When it is announced, it will be at least 2016 blocks (144 * 14, the length of a difficulty adjustment) in the future.
- It will fall on a difficulty adjustment, since that seems more auspicious.
- This gives everyone a fortnight to prepare.

**Comment by casey** [comment]
We should call the activation the etchening.

**Comment by sondotpin** [comment]
Is there any update about activation parameters @casey

**Comment by casey** [comment]
Nope! There is a lot of work still to be done. I need to add wallet commands in particular.

**Comment by qingfeng8814** [comment]
how to inscribe on runes?

**Comment by casey** [comment]
The activation block height is the halving, on block 840,000.
