### ISSUE TITLE
Use deltas for all edict fields

### ISSUE THREAD

**Issue by casey** [casey/runestone#60]
Edict id, amount, and vout are all be deltas. Id is always a delta, amount is a delta if the ID is the same as the last, and output is a delta if the amount is the same as the last.

**Comment by sondotpin** [comment]
How Id can deltas?
what is delta of `{ height: 3, index 1}` and `{ height: 5, index 3}`

**Comment by casey** [comment]
Under realistic circumstances, a block will never have more than 2**16 transactions, so an ID can be encoded as a single number as `height << 16 | index`.

**Comment by casey** [comment]
Edicts are processed in order, so we can't fully reorder them. However, we can reorder edicts by id. So it looks like the best bet is do delta encode edict IDs, but not amounts.
