### ISSUE TITLE
Runestone encode

### ISSUE THREAD

**Issue by sondotpin** [casey/runestone#79]
In the first release of Rune, https://rodarmor.com/blog/runes/ you have define that edict end etching are separated in two data. example:
```
OP_RETURN RUNE_TEST hex1 hex2
```

But in the current implement seems edicts and etching has combine in one hex right?

```
    for edict in &self.edicts {
      varint::encode_to_vec(edict.id, &mut payload);
      varint::encode_to_vec(edict.amount, &mut payload);
      varint::encode_to_vec(edict.output, &mut payload);
    }

    if let Some(etching) = self.etching {
      varint::encode_to_vec(etching.rune.0, &mut payload);

      if etching.divisibility != 0 {
        varint::encode_to_vec(etching.divisibility.into(), &mut payload);
      }
    }
```

is there any conflict? @casey

**Comment by casey** [comment]
Keep in mind that that blog post is completely speculative, and that anything in it is subject to change.

It's not an issue to combine edicts and etching. Each edict is three varints, and if there are one or two trailing varints, that is the etching.
