### ISSUE TITLE
TODO: Define asset ID format

### ISSUE THREAD

**Issue by Psifour** [casey/runestone#8]
"Decide whether or not the ID of an asset is a sequentally assigned ID, or based on the block height and transaction index of the issuance transaction. The former is more compact, but the latter is less ambiguous and allows for compact SPV proofs."

**Comment by summraznboi** [comment]
I like block height and transaction index, but the only correct way of encoding this is 2 integers; there's no good future proof way of combining this into a single integer, and loses out the possibility of using ID deltas. Another possibility that is slightly less compact is to use the symbol itself as the ID (if it is unique).

**Comment by Psifour** [comment]
Strongly support height+txindex, despite the loss of the more optimal format for transfers from #9.
The advantage of being able to reuse a large part of the work that has been done for proofs on Bitcoin is incredibly valuable and would aid in terms of the creation of mobile wallets and other cases where fungible tokens make the most sense to me.

**Comment by owenstrevor** [comment]
I would like to understand how the SPV Proofs work. If this allows users to verify their balances and makes it harder for indexers to rug, it is potentially a breakthrough paradigm for so many use cases.

**Comment by lifofifoX** [comment]
Why is the ID needed in the first place? Is it to track balances for a given wallet? Instead, what if the balances are associated to UTXO and require spending those UTXO in order to spend the balance?

In that case, indexers would primarily only need to track validity of UTXO.

**Comment by jerryfane** [comment]
> I like block height and transaction index, but the only correct way of encoding this is 2 integers; there's no good future proof way of combining this into a single integer, and loses out the possibility of using ID deltas. Another possibility that is slightly less compact is to use the symbol itself as the ID (if it is unique).

What if we interpret transfers as a sequence of `(BLOCKHEIGHT, TXINDEX, OUTPUT, AMOUNT)`. This allows us to apply deltas to both BLOCKHEIGHT and TXINDEX. To address the challenge of sequential TXINDEX from differing blocks, we can introduce wildcards:

- "-" to denote a change from the previous txindex
- "*" to reset the txindex back to an absolute value

Consider the example:

[(800000, 100, 1, 20), (0, 50, 2, 10), (1000, -20, 1, 5), (1000, *200, 15, 50)]

This represents:

1. Block 800000, tx_index 100, output 1, 20 runes
2. Same block, tx_index 150, output 2, 10 runes
3. Block 801000, tx_index 130, output 1, 5 runes
4. Block 802000, reset to tx_index 200, output 15, 50 runes

**Comment by stet** [comment]
`BLOCKHEIGHT:TXINDEX` is usable as an inferred ID. 
I think it would be realized that also having a hard sequential ID is useful (if tickers not unique).

**Comment by casey** [comment]
With unrealistically small transactions, a single block can fit just over 2^16 transactions. These transactions are so small (single input, single output, one byte script pubkey) that the tx index could be safely encoded in 16 bits.

So the asset ID could be defined as `block_height << 16 | tx_index`.

**Comment by jerryfane** [comment]
> With unrealistically small transactions, a single block can fit just over 2^16 transactions. These transactions are so small (single input, single output, one byte script pubkey) that the tx index could be safely encoded in 16 bits.
> 
> 
> 
> So the asset ID could be defined as `block_height << 16 | tx_index`.

If the assumption is right, I agree we should proceed with this approach.

So we'll basically shift the block_height left by 16 bits. This reserves the rightmost 16 bits for the tx_index.
Then we'll insert the tx_index using a bitwise OR. This ensures the combined value is always unique.

**Comment by casey** [comment]
Going with `block_height << 16 | tx_index`
