### ISSUE TITLE
Add command to list all rune balances

### ISSUE THREAD

**Issue by casey** [casey/runestone#84]
Include option to filter by rune, and filter by outputs.

**Comment by owenstrevor** [comment]
Will this work with SPV Proofs?

**Comment by utxo-detective** [comment]
https://github.com/ordinals/ord/pull/2588

**Comment by winktool** [comment]
> [ordinals/ord#2588](https://github.com/ordinals/ord/pull/2588)

how to build script to mint?opcodes?

**Comment by casey** [comment]
Done! You can now call `ord balances` to get the balances of all runes. (`ord wallet balances` was changed in another PR to also display rune balances in the wallet.)
