### ISSUE TITLE
Consider putting rune number in <h1>

### ISSUE THREAD

**Issue by casey** [casey/runestone#91]

**Comment by stet** [comment]
Ha!

**Comment by casey** [comment]
What could go wrong? ;)

**Comment by owenstrevor** [comment]
Feature, not a bug.

**Comment by sondotpin** [comment]
what's different between ```rune_id``` and ```rune_number``` in RuneEntry

**Comment by casey** [comment]
Rune ID is a combination of block height and transaction index. It's represented as `BLOCK/TX`, so `800000/2743` is the rune ID fro a rune created in block 800,000, in the 2743th transaction (counting from 0). The rune number is just assigned sequentially, starting at zero with the first rune, and counting up. The rune ID is nice because if you have it, you can locate the transaction that initially etched the rune. The rune number is more for fun, so people can degen out on low rune numbers.

**Comment by casey** [comment]
I'm thinking we don't do this, since the rune name should be in the h1.
