### ISSUE TITLE
Livestream protocol review once finished

### ISSUE THREAD

**Issue by casey** [casey/runestone#93]
Comment everything, then do a livestream where I go through everything, piece by piece.

**Comment by owenstrevor** [comment]
I recommend using Restream, it's what we use to livestream on Twitter and youtube simultaneously. Twitter also boosts it so it shows in the first slot on the mobile app.

**Comment by a6b8** [comment]
wen?

**Comment by kairinisa** [comment]
There are several issues with titles but without descriptions. Maybe we could do an interim livestream to discuss them verbally? I can then compile summaries to use as descriptions for these issues if it's helpful. @casey

**Comment by casey** [comment]
Closing in favor of #121.
