### ISSUE TITLE
Output/amount ordering bug in edicts

### ISSUE THREAD

**Issue by utxo-detective** [casey/runestone#96]
In the blog it said `These integers are interpreted as a sequence of (ID, OUTPUT, AMOUNT) tuples.`,  but when constructing edicts OUTPUT and AMOUNT are flipped. Is this intended in the implementation or is it a bug?

```rust
for chunk in payload[i + 1..].chunks_exact(3) {
  id = id.saturating_add(chunk[0]);
  body.push(Edict {
    id,
    amount: chunk[1],
    output: chunk[2],
  });
}
```

code is from https://github.com/ordinals/ord/blob/master/src/runes/runestone.rs#L33C9-L40C10

**Comment by casey** [comment]
This is intended in the implementation, It thought that ID, OUTPUT, AMOUNT was more intuitive.
