### ISSUE TITLE
Fractionalizing Ordinal Ownership w/ Runes

### ISSUE THREAD

**Issue by owenstrevor** [casey/runestone#98]
If you issue Runes with an Inscription/Ordinal as the parent in order to fractionalize the ownership, is there a way to create a multi-sig or threshold signature based approach so that the owners of the Runes control the transferring of the Ordinal by a 51% vote? The next step would be listing and then distributing the BTC from a sale.

**Comment by casey** [comment]
This would be possible, but it would have to be done manually, i.e., you would have to move the inscription to a threshold multisig based on the current distribution of runes, and would need to move it again as the distribution changed.
